noize_client:
  hdf5_open_file_path: /home/ericlab/tsuchida/2023_01/annotation/Semseg/HV8/data_1000/1000_not_noize.hdf5
  hdf5_record_file_path: /home/ericlab/tsuchida/2023_01/annotation/Semseg/HV8/data_1000/1000_propose.hdf5

