noize_client:
  hdf5_open_file_path: /home/ericlab/tsuchida/2023_02/image_02/第４章/3d_semantic/normal_copy.hdf5
  hdf5_record_file_path: /home/ericlab/tsuchida/2023_02/image_02/第４章/3d_semantic/noize.hdf5

