decide_object_position:
  z_position: 0.003
  box_height: 0.01
  box_name: denso_box
  radious: 0.05
  sensor_name: phoxi_camera
  sensor_angle_max: 0.087
  sensor_angle_min: 0.087
  distance: 1.1
  object_height: 0.1