annotation_main:
  nearest_radious: 0.002
  radious: 0.05
  the_number_of_dataset: 20
  save_base_file_name: HV8
  occlusion_object_radious: 0.04
  save_dir: /home/ericlab/Pictures/domain_dataset1
  main_object_name: HV8
  quantity_of_main_object: 34
  instance_of_main_object: 1
  other_object_list:
    - object_name: t_pipe
      quantity_of_the_object: 34
      instance_of_the_object: 2
    - object_name: HV7
      quantity_of_the_object: 6
      instance_of_the_object: 3
    - object_name: HV6
      quantity_of_the_object: 6
      instance_of_the_object: 4
  
decide_object_position:
  sensor_name: phoxi_camera
  sensor_angle_max: 0.1
  sensor_angle_min: -0.1
  sensor_distance_min: 0.4
  sensor_distance_max: 0.7
  z_position: 0.003
  box_height: 0.015
  box_name: denso_box
  object_height: 0.15
  radious: 0.05
  sensor_small_deviation: 0.4

data_transform_pkg:
  f_scale: 0.5
  cx_scale: 0.99
  cy_scale: 0.9

data_3D_to_2D:
  radious_x: 0.05
  radious_y: 0.05

noize_image_client:
  small_max_count: 150
  big_max_count: 40

noize_image_make:
  image_height: 1544
  image_width: 2064
  divide_threshold: 100