annotation_main:
  hdf5_record_file_path: /home/dl-box/tsuchida/2023_02/annotation/Semgeg/HV8/no_sensor_4000.hdf5
  nearest_radious: 0.002
  the_number_of_dataset: 4000
  # main_object_name: t_pipe
  # quantity_of_main_object: 34
  # instance_of_main_object: 1
  # radious_of_main_object: 0.04
  # occlusion_radious_of_main_object: 0.02
  main_object_name: HV8
  num_of_main_object: 34
  instance_of_main_object: 1
  radious_of_main_object: 0.05
  occlusion_radious_of_main_object: 0.037
  other_object_list:
    - object_name: t_pipe
      num_of_object: 34
      instance_of_the_object: 2
      occlusion_radious: 0.02
      radious: 0.04
    - object_name: HV7
      num_of_object: 6
      instance_of_the_object: 3
      occlusion_radious: 0.02
      radious: 0.04
    - object_name: HV6
      num_of_object: 6
      instance_of_the_object: 4
      occlusion_radious: 0.033
      radious: 0.05
  
decide_object_position:
  sensor_name: phoxi_camera
  sensor_angle_max: 0.3
  sensor_angle_min: -0.3
  sensor_distance_min: 0.8
  sensor_distance_max: 1.5
  z_position: 0.003
  box_height: 0.01
  box_name: denso_box
  object_height: 0.15
  decide_pose_opition: FullRandom

data_transform_pkg:
  f_scale: 0.5
  cx_scale: 0.99
  cy_scale: 0.9