annotation_main:
  visualize_service_name: visualize_cloud_service
  visualize_image_service_name: visualize_image_service
  sensor_service_name: sensor_service
  hdf5_record_service_name: record_real_sensor_data_service
  hdf5_record_file_path: /home/dl-box/tsuchida/2022_12/annotation/real_data/real_HV8_10.hdf5
  radious: 0.05
  the_number_of_dataset: 10