hdf5_open_server:
  hdf5_open_service_name: hdf5_open_service
  hdf5_real_phoxi_open_service_name: hdf5_real_phoxi_open_service
  hdf5_segmentation_service_name: hdf5_segmentation_service
  hdf5_file_path: /home/ericlab/Downloads/real_data.hdf5

annotation_main:
  visualize_service_name: visualize_cloud_service
  mesh_service_name: mesh_service
  hdf5_record_service_name: record_acc_service
  hdf5_open_service_name: hdf5_real_phoxi_open_service
  tf_br_service_name: tf_broadcast_service
  nearest_radious: 0.002
  the_number_of_dataset: 1
  xyz_step: 0.003
  qxyz_step: 0.01
  main_object_name: HV8
  
decide_object_position:
  sensor_name: phoxi_camera
  sensor_angle_max: 0.087
  sensor_angle_min: 0.087
  sensor_distance_min: 0.8
  sensor_distance_max: 1.5
  z_position: 0.003
  box_height: 0.01
  box_name: denso_box
  object_height: 0.15
  radious: 0.05

data_transform_pkg:
  f_scale: 0.5
  cx_scale: 0.99
  cy_scale: 0.9

data_3D_to_2D:
  radious_x: 0.05
  radious_y: 0.05